steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/flathunters-384915/flathunter-job',
        '-f',
        'Dockerfile.gcloud.job',
        '.',
      ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/flathunters-384915/flathunter-job']
images:
  - gcr.io/flathunters-384915/flathunter-job
